### ISSUE TITLE
v2 0.0.6 not working with wallabag >2.0

### ISSUE THREAD

**Issue by fodiator** [ThibaudDauce/wallabag-firefox#11]
Hi,
I currently have a working wallabag 2.0.3 installed. Unfortunately the current firefox app is not working for me. Maybe because I have wallabag running within a subdirectory of my webserver, which caused a problem with the android app as well.
The latest android app is working now but from my desktop firefox I am unable to add stories. When hitting the wallagbag icon, the login window appears, When adding my credentials "impossiblle to connect" is indicated

I have started the error-logging and this is displayed:
`wallabag-v2:wallabag server undefined, checking configuration… index.js:25
wallabag-v2:Connection error: undefined connection.js:24`
although the server URL is configured correctly

Kind regards

**Comment by ThibaudDauce** [comment]
Hi,

What is your Wallabag URL? Be sure to remove the slash at the end of the URL. 

I will publish a new 0.0.7 version to print all the response in case of failure to have more information on the log `Connection error: undefined` (it's weird that the response status is undefined)

**Comment by fodiator** [comment]
Hi,
URL was & is http://server/wallabag
(without ending slash)

**Comment by ThibaudDauce** [comment]
We must wait the 0.0.7 to debug this because I can't see the logs for the connection error right now. You may install it from the release page (https://github.com/ThibaudDauce/wallabag-firefox/releases/tag/0.0.7) and give me again the logs (hopefully there will be some information)

**Comment by fodiator** [comment]
I have just installed and tested 0.0.7
Login window shows the correct language now. Storing an atricle still doesn't work. 
Here's the log:
`wallabag-v2:  wallabag server undefined, checking configuration… index.js:61
POST XHR   http://server/wallabag/oauth/v2/token [HTTP/1.1 400 Bad Request 49ms]
wallabag-v2:  Connection error: [object Object]`

**Comment by ThibaudDauce** [comment]
I'm sorry I made a bad mistake in https://github.com/ThibaudDauce/wallabag-firefox/commit/80c728d2789c50d416e94bea596b5b3b7adebbbf (the reason why there is "[object Object]" in the `console.log()`). I hope https://github.com/ThibaudDauce/wallabag-firefox/commit/ca2ec2cd670ffa57f2f3e020480b81d8a47db3df will fix it. 

Just wait the Mozilla validation or download and install the XPI from Github release page https://github.com/ThibaudDauce/wallabag-firefox/releases/tag/0.0.8 and try again :-( Sorry (I hope I will get more information in from the wallabag response)

**Comment by fodiator** [comment]
Installed 0.0.8
tried to add an article, here is the log:
`wallabag-v2:Connection error: connection.js:24`
`wallabag-v2:Object { error: "invalid_client", error_description: "The client credentials are invalid" } connection.js:25`

**Comment by ThibaudDauce** [comment]
Nice!

It seems to be a problem with your Client ID and client secret… Maybe try to generate a new client from your wallabag server and change the configuration?

**Comment by fodiator** [comment]
Created a new test user - same result :-(
(By the way: adding articles with the android app is working, so login through ID and PW must be working)

**Comment by ThibaudDauce** [comment]
I think the android app is not using the API (so no client ID and no client secret…)
I'm not speaking of a user but a new client API IDs. Go to the "developer" menu, then "Add new client", put `http://localhost` for the redirect URL and copy paste the client ID and the client secret in the addon configuration (about:addons).

**Comment by fodiator** [comment]
Did it - same result
Even when I put the credentials into the addon-settings, when I hit the wallabag icon > the login window appears whith empty credentials

**Comment by ThibaudDauce** [comment]
There is 4 credentials : login, password, client ID and client secret. Client ID and client secret goes to the add-on settings (and they're never shown on the login window) you need to generate them from your wallabag web interface in the developer menu (it's two strings looking like `3_1smt9falhfuscg0csgk48ksks8k40w8004w0o4scc8ckkokw4k` and `uablpnshrdccw8kc08sgkc4kk04080wcw80kkgkowg4sow04g`), login and password are the two information you use on the wallabag web interface to connect (and on the login window during the first page saved with the add-on).

**Comment by fodiator** [comment]
Got it!
It's working now.
How do I delete the testuser credentials and use my account now?

**Comment by ThibaudDauce** [comment]
You can't disconnect :-( Try to revoke the client ID and client secret in your wallabag instance and save a page (it should detect you're not allowed to connect anymore…)

And if it's not working , you can remove the add-on and reinstall it…

**Comment by fodiator** [comment]
Puhhhh!
This was a long run, but it's finally working!
THX for your support &
keep up the good work!

**Comment by ThibaudDauce** [comment]
Thanks, don't hesitate if you have any new problem!
