### ISSUE TITLE
Ability to change language 

### ISSUE THREAD

**Issue by bigretromike** [ThibaudDauce/wallabag-firefox#7]
Im using English Firefox (nightly) and when adding URL with this plugin i get French messages.

**Comment by ThibaudDauce** [comment]
It's because the application is not yet translated. We need to replace all the french sentence (done in #5 ) and then add all strings in the locale folder https://github.com/ThibaudDauce/wallabag-firefox/tree/master/locale.

You can make a PR if you want :-)

**Comment by bigretromike** [comment]
Is there full skeleton for localization file, I could make one for other language also

**Comment by ThibaudDauce** [comment]
The only place where we use localization file is https://github.com/ThibaudDauce/wallabag-firefox/blob/b8552e4e4aa6e6df8e9f668349f904a503fadfeb/configuration.js with `_("cfg_required_msg")` for example. We need to replace all english sentences in the JavaScript files with this syntax and fill the english locale file https://github.com/ThibaudDauce/wallabag-firefox/blob/b8552e4e4aa6e6df8e9f668349f904a503fadfeb/locale/en.properties then we will be able to translate to other language I think.

**Comment by ThibaudDauce** [comment]
For HTML, we need to add `data-l10n-id` attributes:
```html
<html>
  <body>
    <h1 data-l10n-id="hello_id"></h1>
  </body>
</html>
```

See https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/l10n and https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/l10n for more information

**Comment by bigretromike** [comment]
Oh I see. So its not implemented yet then. I will wait till I see english translation in plugin that will be sign that I can help with other translations ;-)

**Comment by ThibaudDauce** [comment]
Could you extract the english sentences in the english local file? :-D
