### ISSUE TITLE
Trying to add url result in not doing it

### ISSUE THREAD

**Issue by bigretromike** [ThibaudDauce/wallabag-firefox#8]
Sometimes when I hit "W" button I get French message about trying to add page but its on white background and it never go on green one.

When normally I'm adding page I get yellowish background and then turning green.

**Comment by ThibaudDauce** [comment]
Could you go to `about:config` and add a new key: `extensions.@wallabag-v2.sdk.console.logLevel` with the value `all`.

Maybe restart your Firefox. Then open the developer console (Ctrl-Shift-J on my computer) 
and filter the logs with the search bar (search for "wallabag"). Could you send me the result 
after trying to connect?

**Comment by bigretromike** [comment]
this is for yellow background will try to get white one with logs.
For yellow bar it looks like it refresh token (why?) and then never change the message to complete (or dont try to readd once again)

```
wallabag-v2:Access token existing, trying to create a server…index.js:16
wallabag-v2:Wallabag server is ready! I can post!index.js:61
wallabag-v2:"I'm gonna add https://github.com/ThibaudDauce/wallabag-firefox/issues/8#issuecomment-212789321 on the https://<domain>/api/entries!"server.js:16
wallabag-v2:Access token expired. Trying to refresh with 1_token and <secret> index.js:75
wallabag-v2:Object {  }connection.js:64
wallabag-v2:Object { access_token: "MDgzYTJlYTNmZDAyNmUyMjkwM2FiYz5ZjJ…", expires_in: 3600, token_type: "bearer", scope: null, refresh_token: "M2UwMjJmNzQyODNkYmRjMGJjZWMODk4MTg…" }index.js:77
wallabag-v2:Access token refreshed.index.js:81
```

**Comment by ThibaudDauce** [comment]
The access token is only valid for one hour, the client need to send a new request to get a new access token (with the refresh token which is valid much longer). This problem is fix in https://github.com/ThibaudDauce/wallabag-firefox/commit/f822290aa194da43a215f03c7ad740f557acc33d I think

**Comment by bigretromike** [comment]
^_^ waiting for update. thanks

If I came across white background message about having to wait I will parse log.

**Comment by ThibaudDauce** [comment]
Can I close this issue with the new release? Is it working for you?

**Comment by bigretromike** [comment]
yes - didnt happend after updating
